import styles from '@/styles/Layout.module.css'
import LibraryIcon from '@/svgs/library.svg'
import TicketLogo from '@/svgs/solidTicket.svg'
import { Box, Container, Flex, Text } from '@chakra-ui/react'
import Head from 'next/head'
import Link from 'next/link'
import { FC, ReactNode } from 'react'
import SearchBar from './SearchBar'

const Layout: FC<{ children: ReactNode }> = ({ children }) => {
  return (
    <>
      <Head>
        <title>TicketStub</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.png' />
      </Head>
      <main className={styles.main}>
        <Container maxW={768} minW={375} paddingTop={[1, 3]}>
          <Flex justifyContent={'space-between'} alignContent={'flex-end'}>
            <Link href={'/'}>
              <Flex>
                <TicketLogo height={40} width={40} className={styles.logo} />
                <Text fontSize={'4xl'} fontWeight={'extrabold'}>
                  TicketStub
                </Text>
              </Flex>
            </Link>
            <Link href={'/'} className={styles.library}>
              <LibraryIcon height={40} width={40} />
            </Link>
          </Flex>
          <SearchBar />
          <Box height={[2, 4]} />
          {children}
        </Container>
      </main>
    </>
  )
}

export default Layout
